
package com.cmg.mobitelPay.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MCAccMgr", targetNamespace = "http://ws/", wsdlLocation = "https://mcg.mobitel.lk/M_CGW/MCAccMngr?wsdl")
public class MCAccMgr
    extends Service
{

    private final static URL MCACCMGR_WSDL_LOCATION;
    private final static WebServiceException MCACCMGR_EXCEPTION;
    private final static QName MCACCMGR_QNAME = new QName("http://ws/", "MCAccMgr");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mcg.mobitel.lk/M_CGW/MCAccMngr?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MCACCMGR_WSDL_LOCATION = url;
        MCACCMGR_EXCEPTION = e;
    }

    public MCAccMgr() {
        super(__getWsdlLocation(), MCACCMGR_QNAME);
    }

    public MCAccMgr(WebServiceFeature... features) {
        super(__getWsdlLocation(), MCACCMGR_QNAME, features);
    }

    public MCAccMgr(URL wsdlLocation) {
        super(wsdlLocation, MCACCMGR_QNAME);
    }

    public MCAccMgr(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MCACCMGR_QNAME, features);
    }

    public MCAccMgr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MCAccMgr(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MCAccMngr
     */
    @WebEndpoint(name = "MCAccMngrPort")
    public MCAccMngr getMCAccMngrPort() {
        return super.getPort(new QName("http://ws/", "MCAccMngrPort"), MCAccMngr.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MCAccMngr
     */
    @WebEndpoint(name = "MCAccMngrPort")
    public MCAccMngr getMCAccMngrPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "MCAccMngrPort"), MCAccMngr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MCACCMGR_EXCEPTION!= null) {
            throw MCACCMGR_EXCEPTION;
        }
        return MCACCMGR_WSDL_LOCATION;
    }

}
