
package com.cmg.mobitelPay.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MCAccMngr", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MCAccMngr {


    /**
     * 
     * @param msisdn
     * @return
     *     returns ws.InfoResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "msisdnInfo", targetNamespace = "http://ws/", className = "ws.MsisdnInfo")
    @ResponseWrapper(localName = "msisdnInfoResponse", targetNamespace = "http://ws/", className = "ws.MsisdnInfoResponse")
    public InfoResult msisdnInfo(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn);

    /**
     * 
     * @param passWord
     * @param chgRequest
     * @param userName
     * @return
     *     returns ws.ChgResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "chargeFromMSISDN", targetNamespace = "http://ws/", className = "ws.ChargeFromMSISDN")
    @ResponseWrapper(localName = "chargeFromMSISDNResponse", targetNamespace = "http://ws/", className = "ws.ChargeFromMSISDNResponse")
    public ChgResult chargeFromMSISDN(
        @WebParam(name = "chgRequest", targetNamespace = "")
        ChgRequest chgRequest,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "passWord", targetNamespace = "")
        String passWord);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ws/", className = "ws.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ws/", className = "ws.HelloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param msisdn
     * @return
     *     returns ws.BalanceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkBalance", targetNamespace = "http://ws/", className = "ws.CheckBalance")
    @ResponseWrapper(localName = "checkBalanceResponse", targetNamespace = "http://ws/", className = "ws.CheckBalanceResponse")
    public BalanceResult checkBalance(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn);

    /**
     * 
     * @param msisdn
     * @return
     *     returns ws.BalanceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkPrepaidBalance", targetNamespace = "http://ws/", className = "ws.CheckPrepaidBalance")
    @ResponseWrapper(localName = "checkPrepaidBalanceResponse", targetNamespace = "http://ws/", className = "ws.CheckPrepaidBalanceResponse")
    public BalanceResult checkPrepaidBalance(
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn);

}
